stages:
  - test

include:
  - project: '715-scrum1/grp_moodle/ci-cd-templates'
    file:
      - 'moodle-plugin-ci.yml'

moodle_plugin_ci:
  parallel:
    matrix:
      - MOODLE_BRANCH: [ MOODLE_401_STABLE]
        MOODLE_PHP_IMAGE: ["moodlehq/moodle-php-apache:8.0"]
        POSTGRES_IMAGE: ["postgres:14-alpine"]
